version: 2.1

# Define the jobs we want to run for this project
jobs:
  deploy:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: echo "$(pwd)"
      - run: ls -la
      - run: ssh -i"test_ec2_linux.pem" ubuntu@ec2-34-211-44-48.us-west-2.compute.amazonaws.com

# Orchestrate our job run sequence
workflows:
  deployer:
    jobs:
      - deploy