version: 2.1

# Define the jobs we want to run for this project
jobs:
  deploy:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: echo "$(pwd)"
      - run: ls -la
      - run: sudo chown -R $USER .
      - run: ls -la
      - run: sudo ssh -i "./pkey/circleci.pem" -o "StrictHostKeyChecking no" admin@ec2-52-13-56-181.us-west-2.compute.amazonaws.com
      - run: sudo su
      - run: ls -la

# Orchestrate our job run sequence
workflows:
  deployer:
    jobs:
      - deploy