version: 2.1

# Define the jobs we want to run for this project
jobs:
  deploy:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: echo "$(pwd)"
      - run: cd ./${CIRCLE_PROJECT_REPONAME}

# Orchestrate our job run sequence
workflows:
  deployer:
    jobs:
      - deploy