version: 2.1

# Define the jobs we want to run for this project
jobs:
  deploy:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: git update-index --chmod=+x ./deploy.sh
      - run: ./deploy.sh

# Orchestrate our job run sequence
workflows:
  deployer:
    jobs:
      - deploy